- name: update and upgrade apt packages
  become: yes
  apt:
    upgrade: yes
    update_cache: yes
  
- name: Install nessesary packages
  become: yes
  apt:
    name: "{{ support_packages }}"

- name: One way to avoid apt_key once it is removed from your distro
  block:
    - name: somerepo |no apt key
      get_url:
        url:  "{{ base_url }}gpg"
        dest: "{{ keyring }}"

    - name: somerepo | apt source
      apt_repository:
        repo: "deb [arch={{ ansible_architecture }} signed-by={{ keyring }}] {{ base_url }} {{ ansible_distribution_release }} stable"
        state: present

- name: update and upgrade apt packages
  become: yes
  apt:
    upgrade: yes
    update_cache: yes

- name: install docker package
  apt:
    name: "{{ docker_package }}"
    state: present

